global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets:
        - admin:9100
        - auth:9100
        - wss:9100
        - monitoring:9100
        - mysql:9100
        - redis:9100
        - freeswitch:9100
        - kamailio:9100
        - xmpp:9100
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets:
        - mysql:9104
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - redis:9121
